# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

steps:

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'azure app service'
    subscriptionId: '7122b890-4d38-46fb-8c3d-9e0a76c39cc6'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'app_service'
    location: 'North Europe'
    templateLocation: 'Linked artifact'
    csmFile: './azuredeploy.json'
    csmParametersFile: './azuredeploy.parameters.json'
    deploymentMode: 'Incremental'

